parameters:
#    nabli_admin.example.class: Nabli\AdminBundle\Example

services:
#    nabli_admin.example:
#        class: %nabli_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
