parameters:
#    nabli_event_stream.example.class: Nabli\EventStreamBundle\Example

services:
#    nabli_event_stream.example:
#        class: %nabli_event_stream.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
