imports:
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        use_cdn: "%twig_use_cdn%" 

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [NabliEspManBundle,NabliWebBundle,NabliAppBundle,NabliAuthBundle,FOSUserBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: C:\\Program Files\\nodejs\\node
            node_paths: [C:\\Users\\gerkna\\AppData\\Roaming\\npm\\node_modules]
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Twitter Bootstrap
braincrafted_bootstrap:
    output_dir: twbs
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
    less_filter: less # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/twbs/fonts
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

# FOS User Bundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: klaudnabli_secured
    user_class: Nabli\AuthBundle\Entity\User
    registration:
        form:
            type: nabli_user_registration
        confirmation:
            enabled:    true
    from_email:
        address:        noreply@klaudnabli.com
        sender_name:    KlaudNabli Authentification



hwi_oauth:
    connect:
        account_connector: oauth_user_provider
    firewall_name: klaudnabli_secured
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
            google: google_id
            twitter: twitter_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_app_id%"
            client_secret:       "%facebook_app_secret%"
            scope:               "%facebook_app_scope%"
            infos_url:           "https://graph.facebook.com/me/?fields=id,name,first_name,last_name,email,link,age_range,gender,timezone,locale,verified,picture.type(large)"
            user_response_class: Nabli\AuthBundle\Security\Core\User\ExtendedPathUserResponse
            paths:
                identifier:      id
                nickname:        name
                realname:        name
                email:           email
                profilepicture:  picture.data.url
                profilelink:     link
                firstname:       first_name 
                lastname:        last_name
                gender:          gender
                #age_group:
                locale:          locale
                timezone:        timezone
                verified:        verified
        google:
            type:                google
            client_id:           "%google_app_id%"
            client_secret:       "%google_app_secret%"
            scope:               "%google_app_scope%"
            user_response_class: Nabli\AuthBundle\Security\Core\User\ExtendedPathUserResponse
            paths:
                identifier:      id
                nickname:        name
                realname:        name
                email:           email
                profilepicture:  picture
                profilelink:     link
                firstname:       given_name 
                lastname:        family_name
                #gender:         
                #age_group:
                locale:          locale
                #timezone:
                verified:        verified_email
        twitter:
            type:                twitter
            client_id:           "%twitter_app_id%"
            client_secret:       "%twitter_app_secret%"
            scope:               "%twitter_app_scope%"
            user_response_class: Nabli\AuthBundle\Security\Core\User\ExtendedPathUserResponse
            paths:
                identifier:      id_str
                nickname:        screen_name
                realname:        name
                #email:           email
                profilepicture:  profile_image_url_https
                profilelink:     url
                #firstname:       
                #lastname:
                #gender:
                #age_group:
                locale:          lang
                timezone:        time_zone
                verified:        verified
