parameters:
#    nabli_web.example.class: Nabli\WebBundle\Example

services:
#    nabli_web.example:
#        class: %nabli_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
