parameters:
#    nabli_esp_man.example.class: Nabli\EspManBundle\Example

services:
#    nabli_esp_man.example:
#        class: %nabli_esp_man.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
