parameters:
#    nabli_insight_provider.example.class: Nabli\InsightProviderBundle\Example

services:
#    nabli_insight_provider.example:
#        class: %nabli_insight_provider.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
