parameters:
#    nabli_content_provider.example.class: Nabli\ContentProviderBundle\Example

services:
#    nabli_content_provider.example:
#        class: %nabli_content_provider.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
